# Practice 1: Control flow

Ex2:Write a program to determine if 3 distinct points create an acute, right, obtuse triangle or a straight line, given the coordinates of the points

In [ ]:
import math


ax, ay, bx, by, cx, cy= [float(i) for i in input().split()]
L1=math.sqrt((ax-bx)**2+(ay-by)**2)
L2=math.sqrt((ax-cx)**2+(ay-cy)**2)
L3=math.sqrt((bx-cx)**2+(by-cy)**2)
if (L1+L2>L3) and (L1+L3>L2) and (L2+L3>L1):
    if (L1**2+L2**2<L3**2) or (L1**2+L3**2<L2**2) or (L2**2+L3**2<L1*2):
        print('Obtuse triangle')
    elif (L1**2+L2**2==L3**2) or (L2**2+L3**2==L1**2) or (L1**2+L3**2==L2**2):
        print('Right triangle')
    elif (L1**2+L2**2>L3**2) and (L2**2+L3**2>L1**2) and (L1**2+L3**2>L2**2):
        print('Acute triangle') 
else:
    print('Straight line')      

3 7 8 9 2 1
Obtuse triangle


Ex3:GrabBike's pricing in Hanoi is calculated as follow: for the first 2km, the customer will be charged VND 12,000 and for each next km, he will be charged VND 3,500. In addition, after the first 2km, the customer will be charged VND 350 for each minute travel.

Given the distance and the average speed (assume that the speed is constant), calculate the amount of money that the customer has to pay



In [ ]:
distance=float(input())
speed=float(input())
if (distance<=2):
  price=12000
else: 
  time=(distance-2)/speed
  price=12000+time*350+(distance-2)*3500
print('{:.2f}'.format(price))    





1.   Exercise 4
The Collatz conjecture is a conjecture in mathematics that concerns a sequence defined as follows: start with any positive integer n. If the previous term is even, the next term is one half of the previous term. If the previous term is odd, the next term is 3 times the previous term plus 1. The conjecture is that no matter what value of n, the sequence will always reach 1.

For instance, starting with n = 12, one gets the sequence 12, 6, 3, 10, 5, 16, 8, 4, 2, 1.

Given the starting number, print the value of all the numbers in its path to 1



In [ ]:
n=int(input())
print(n,end=' ')
while (n!=1):
  if n%2==0:
    n/=2
  else:
    n*=3
    n+=1
  print(int(n),end=' ')

42
42 21 64 32 16 8 4 2 1 

Exercise 5
Write a program to check if an integer is a prime number or not

In [ ]:
from math import*


n=int(input())
Check=False
if (n<=1):
  print(Check)
if (n==2) or (n==3):
  Check=True
  print(Check)
elif (n>=4):
  Check=True
  r=int(sqrt(n))
  for i in range(2,r+1):
    if (n%i==0):
      Check=False
      break
  print(Check)

61683248493
False


Exercise 6
Print a shape that looks like the one below, given the height

In [ ]:
n=int(input())
i=1
st='\\'
while i in range(n+1):
  print('_'*(n-i)+'/'+' '*(i*2-2)+st+'_'*(n-i))
  i+=1


3
__/\__
_/  \_
/    \


Exercise 7
One way of computing square roots is Newton's method. Suppose that you want to know the square root of a. If you start with (almost) any estimate x, then you can get a better estimate with the formula: y = (x + a/x)/2

Given a non-negative number a, compute the square root of that number using Newton's method with the precision of 0.0000001

In [ ]:
from random import*
x = uniform(0,10000)
a=float(int(input()))
while (abs(x**2-a)>=0.0000001):
  x=(x+(a/x))/2
print('{:.7f}'.format(x))

32
5.6568542


Exercise 8
Using the code from exercise 7 and math.sqrt function from math library, print a table that describe the differences between the estimation in each step and the value computed by math.sqrt function



An Amstrong number of 3 digit is an integer that the sum of 
the cubes of its digits is equal to the number itself. Find 
Amstrong numbers of 3 digits

In [ ]:
for i in range(100,1000,1):
  c=i%10
  b=((i-c)%10)%10
  a=i//100
  if (a**3+b**3+c**3==i):
    print(i)

407


# Practice 1: Control flow(Part 2)

Write a program that takes a positive integer n as input and returns the sum of all that number's digits.

In [ ]:
n=input()
sum=0
for i in n:
  sum+=int(i)
print(sum)  


12345678
36


Write a program to display the pattern like a diamond.

Input:

A single line that contains a positive number n

Output:

There are 2n-1 lines in total. The i-th line contains n-i spaces and 2*i-1 asterisks if 1 ≤ i ≤ n, and contains i-n spaces and 2(2n-i)-1 asterisks if n < i ≤ 2n-1.

In [ ]:
n=int(input())
i=1
while (i<=n):
  print(' '*(n-i)+'*'*(2*i-1)+' '*(n-i))
  i+=1
while (i<=2*n-1):
  print(' '*(i-n)+'*'*(4*n-2*i-1)+' '*(i-n))
  i+=1  

8
       *       
      ***      
     *****     
    *******    
   *********   
  ***********  
 ************* 
***************
 ************* 
  ***********  
   *********   
    *******    
     *****     
      ***      
       *       


Fibonacci sequence Fn is the sequence such that each number is the sum of the two preceding ones, starting from 0 and 1.

F0 = 0, F1 = 1, 

Fn = Fn-1 + Fn-2, n ≥ 2

Your task is to write a program that takes an integer n as input and output the n-th Fibonacci number

In [ ]:
n=int(input())
if n==0:
  sum=0
if n==1:
  sum=1
else:
  first=0
  second=1
  for i in range(n-1):
      sum=first+second
      first=second
      second=sum
print(sum)  
      

150
9969216677189303386214405760200


Write a program to display such a pattern for n number of rows using a number that will start with the number 1 and the first and the last number of each row will be 1.



In [ ]:
n=int(input())
i=1
while i<=n:
  space=' '*(n-i)
  for j in range(1,i):
    space+=str(j)
  space+=str(i)  
  for j in range (i-1,0,-1):
    space+=str(j)
  i+=1
  print(space)  



4
   1
  121
 12321
1234321


In [ ]:
def prime(a):
    if a<=1:
        return False
    for i in range(2, int(a ** 1/2) + 1):
        if a % i == 0:
            return False
    return True
    def prime(a):
    if a<=1:
        return False
    for i in range(2, int(a ** 1/2) + 1):
        if a % i == 0:
            return False
    return True

def if_sum_of_2_primes(a):
    for i in range(2, int(a/2)):
        if prime(i) and prime(a-i):
            return True
    return False

n = int(input())
for i in range(n):
    x = int(input())
    if if_sum_of_2_primes(x):
        print('YES')
    else:
        print('NO')

# Practice3: Strings, list, dictionaries and tuples

Exercise 1
Write a program to print a string consists of every second character of the string in reverse order starting from the last one and with the first character in the result string capitalized (the other characters are lowercase)

Example: Input: abcdefg, Output: Geca


In [ ]:
print(input()[::-2].capitalize())




ab
B


Exercise 2
In naming convention of some languages, variables are often named using Camel case convention (for example: ArrayOfNumber), while in other languages (including Python), variables are named using Snake case convention (for example: array_of_number)

Write a program to convert a string from Snake case to Camel case

Example: Input: array_of_number, Output: ArrayOfNumber

In [ ]:
s=input()
n=len(s)
for i in range(n):
  if s[i]=='_':
    s=s.replace(s[i],' ')
s=s.title()
s=s.replace(' ','')
print(s)    


array_of_number
ArrayOfNumber


Exercise 3
Write a program to remove all the uneccessary spaces from a string, including leading, trailing whitespaces and multiple whitespaces in the middle of the sentence

For example:\ Input:

   Hello   World from   Vietnam
Output:

Hello World from Vietnam

In [ ]:
import re
print(re.sub(' +', ' ', input()).strip())



     Say        hi     from     Vietnam
Say hi from Vietnam


Exercise 4
Write a function that returns the mirror image of a string (contains lowercase characters only) if that mirror image is still a valid string. Otherwise, return "NOT POSSIBLE".

Note: b,d, i, o, p, q, v, w, x are characters with the mirror images still valid English characters

Example: Input: void, Output: biov

In [ ]:
def reverse(s):
  m=''
  i=len(s)
  while i>0:
    m+=s[i-1]
    i-=1
  return m  
def mirror(s):
  dict={'b':'d','d':'b','i':'i','o':'o','p':'q','q':'p','v':'v','w':'w','x':'x',' ':' '}
  res=''
  s=reverse(s)
  for c in s:
    if c in dict:
      res+=dict[c]
    else:
      res='NOT POSSIBLE'
      break
  return res 
s=input()
print(mirror(s))



biov biov
void void


In [ ]:
def transform_string(s):
    i=len(s)-1
    newstr=''
    if (i+1)%4==0:
        while i>=0:
            newstr+=s[i]
            i-=1
    else:
        for i in range(i+1):
            if i%2==0:
                newstr+=s[i+1]
    return newstr
print(transform_string('Dai hoc bach khoa ha noi'))
print(transform_string('DHBKHN'))

ion ah aohk hcab coh iaD
HKN


Write a function to remove all consecutive duplicates in a list and return the new list

Example:\ Input

[1, 0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4, 5, 5]
Output

[1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 5]

Part2:Basic tuples, lists and dictionaries

Exercise 5
Write a function to remove all consecutive duplicates in a list and return the new list

Example:\ Input

[1, 0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9, 4, 4, 5, 5]
Output

[1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 5]

In [ ]:
def remove_duplicates(s):
    previous_value=None
    newlist=[]
    for i in x:
      if i!=previous_value:
        newlist.append(i)
        previous_value=i
    print(newlist)
x=[1,0,0,2,3]
remove_duplicates(x)        

 


[1, 0, 2, 3]


Exercise 6
Write a program to read 2 matrices and output their sum. Example:

Input (the first line contains 2 dimensions M * N of each matrix, the next M lines contains the first matrix and the last M lines contains the second matrix)

In [ ]:
size=input().split()
m,n=int(size[0]),int(size[1])
a=[]
b=[]
for i in range(m):
  a.append(input().split(' '))
for i in range(m):
  b.append(input().split(' '))
for i in range(m):
  for j in range(n):
    print(int(a[i][j])+int(b[i][j]),end=' ')
  print('')      

2 3 
1 2 3
4 5 6
7 8 9
10 11 12
8 10 12 
14 16 18 


Exercise 7
Write a function to sort the list of tuples of students by the students' scores. If they have the same scores, sort the students by their names.

Example:\ Input

[('John', 9.75), ('Max', 9.5), ('James', 9.5), ('Henry', 8.5)]
Output

[('Henry', 8.5), ('James', 9.5), ('Max', 9.5), ('John', 9.75)]
Hint: use sorted function with key for quick sorting (or implement your own sort function)

In [ ]:
def sort_students(l):
    x=sorted([(v,k) for k,v in l])
    y=[(v,k) for k,v in x ]
    return y
print(sort_students([('John', 9.75), ('Max', 9.5), ('James', 9.5), ('Henry', 8.5)]))    

[('Henry', 8.5), ('James', 9.5), ('Max', 9.5), ('John', 9.75)]


Ex8:Write a function that return a dictionary of each character frequency in the string
For example:

Test	Result
print(dictionary_convert('edcbaabcd'))
# {'e': 1, 'd': 2, 'c': 2, 'b': 2, 'a': 2}

In [ ]:
def dictionary_convert(s):
    counts=dict()
    for word in s:
        counts[word] = counts.get(word, 0) + 1
    return counts

Ex9: Write a function using list comprehension that takes a list as input and return the list with all even numbers doubled, and all odd numbers turned negative

In [ ]:
def transform(l):
    x=[]
    for i in l:
        if i%2==0:
            x.append(i*2)
        else:
            x.append(i*(-1))
    return x

Write a program using list comprehension that print a matrix consists of increasing element (starting from 1), given its dimension

In [ ]:
tmp=input().split(' ')
m,n=int(tmp[0]),int(tmp[1])
a=1
for i in range(m):
    for j in range(n):
        print(a,end=' ')
        a+=1
    print(''

Write a program using list comprehension that returns the Caesar encryption of a lowercase string, given the shift length. Note: in Caesar encryption, each letter is shifted to the right in the alphabet by a distance (if the end of the alphabet is reached, the shift will start over from letter a)

In [ ]:
n=int(input())
s=input()
dic=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
result=[dic[(dic.index(i)+n)%26] if i in dic else ' ' for i in s]
for re in result:
    print(re,end='')

Write a function to compute the distance between 2 vectors (it is guarantee that the 2 vectors have the same shape). Type of distance is a keyword argument, which can be either 'manhattan', 'cosine' (with 9 decimal places), or 'euclidean' (with 1 decimal place). If no type of distance or other types of distance is specified, the distance will be computed with euclidean norm

In [ ]:
from math import sqrt

def vector_distance(v1, v2, **kwargs):
    a=dict(**kwargs)
    m=0
    l1=0
    l2=0
    if len(a)==0:
        a={'norm':'euclidean'}
    if a['norm']=='euclidean':
        for i in range(len(v1)):
            m+=(v1[i]-v2[i])**2
        m='{:.1f}'.format(sqrt(m))
    elif a['norm']=='manhattan':
        for i in range(len(v1)):
            m+=abs(v1[i]-v2[i])
    elif a['norm']=='cosine':
        for i in range(len(v1)):
            m+=v1[i]*v2[i]
            l1+=v1[i]**2
            l2+=v2[i]**2
        m='{:.9f}'.format(m/(sqrt(l1)*sqrt(l2)))
    return m

# Slides:Functions:In class 

Write a function is_prime(n) to check if n is a prime number or not. The function returns True if n is a prime number, and return False otherwise.

In [ ]:
def is_prime(a):
    if a<=1:
        return False
    for i in range(2, int(a ** 1/2) + 1):
        if a % i == 0:
            return False
    return True


Write a function prime_list(k) to print all prime numbers that are not greater then k.

For example:

Test	Result
prime_list(20)
prime_list(10)
2 3 5 7 11 13 17 19
2 3 5 7


In [ ]:
def prime(a):
    if a<=1:
        return False
    for i in range(2, int(a ** 1/2) + 1):
        if a % i == 0:
            return False
    return True
def prime_list(k):
    for i in range(2,k+1):
        if prime(i):
            print(i, end = ' ')
    print()

In [ ]:
def sum(n,k):
    h=0
    for i in range(1,n+1):
        if i%k!=0:
            h+=i
    print(h,end=' ')
    return ''

# In class recursive

Write a recursive function gd(a, b) to find the greatest common divisor of 2 positive integers.

In [ ]:
def gd(a,b):
    if b==0:
        return a
    if a==0:
        return b
    if (a!=0) and (b!=0):
        if a>b:
            return gd(a%b,b)
        else:
            return gd(a,b%a)

Write a recursive function f(n) to calculate the n-th element of the following sequence:

a1 = 1, a2 = 2, an = an-1 + 2 * an-2

In [ ]:
def f(n):
    if n==1:
        return 1
    if n==2:
        return 2
    if n>2:
        return f(n-1)+2*f(n-2)

Write a function binary(n) to compute the number of binary strings of length n that do not contain two successive zeros.

For example:

Test	Result
print(binary(1))
print(binary(3))
2
5
Answer:(penalty regime: 10, 20, ... %)


Let a[i] be the number of binary strings of length i which do not contain any two consecutive 1’s and which end in 0. Similarly, let b[i] be the number of such strings which end in 1. We can append either 0 or 1 to a string ending in 0, but we can only append 0 to a string ending in 1

# Practice2: Functions

In number theory, a perfect number is a positive integer that is equal to the sum of its proper positive divisors, that is, the sum of its positive divisors excluding the number itself.

Write a function is_perfect(n) to check whether a given number n is a perfect number or not.

In [ ]:
def is_perfect(n):
    sum=0
    for i in range(1,n):
        if n%i==0:
            sum+=i
    if sum==n:
        return True
    else:
        return False

Write a Python function to print the first n<sup>th</sup> lines (n > 0) of the Pascal triangle. Note: you can define additional functions for better use

In [ ]:
from math import factorial
def pascal_triangle(n):
    for i in range(n):
        for j in range(i + 1):
            # nCr = n!/((n-r)!*r!)
            print(factorial(i) // (factorial(j) * factorial(i - j)), end=" ")

        # for new line
        print()
pascal_triangle(5)

1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 


# In-class strings

Write a function transform_string(str) to reverse the input string if its length is a multiple of 4, or remove all characters with even indices otherwise.

In [ ]:
def transform_string(s):
  i = len(s) - 1
  newstr = ''
  if (i + 1) % 4 == 0:
    while i >= 0:
      newstr += s[i]
      i -= 1
  else:
    for i in range(i + 1):
      if i % 2 == 1:
        newstr += s[i]
  return newstr
print(transform_string('DHBKHN'))
print(transform_string('Dai hoc Bach Khoa Ha Noi'))

HKN
ioN aH aohK hcaB coh iaD


Write a function last_repeat(str) to return the last non-space repeated character in the input string. The function returns 'None' if there is no such a repeated character.



In [ ]:
def last_repeat(s):
    char_appear=[]
    counts={}
    s=s.strip().replace(' ','')
    for c in s:
        if c in counts:
            counts[c]+=1
        else:
            counts[c]=1
    for c in s:
        if counts[c]>1:
            char_appear.append(c)
    n=len(char_appear)
    if n>=1:
        return char_appear[n - 1]
    else:
        return None
print(last_repeat(' Dai hoc Bach khoa  '))
print(last_repeat('BKHN'))

a
None


# Practice 3: Part 2-Homework


Write a recursive function display_pascal_triangle(n) to display a Pascal triangle with n rows, where n is a given positive integer.

The i-th row contains n-i spaces followed by Binomial coefficients C(0,i-1), C(1,i-1),..., C(i-1,i-1), which are separated by spaces, i = 1, 2,..., n

In [ ]:
from math import factorial
def display_pascal_triangle(n):
    for i in range(n-1):
        print((n-i-2)*' ',end=' ')
        for j in range(i+1):
            print((factorial(i)//(factorial(j)*factorial(i-j))),end=' ')
        print()
    for j in range(n):
        print((factorial(n-1) // (factorial(j) * factorial(n-1 - j))), end=' ')
print(display_pascal_triangle(6))        

     1 
    1 1 
   1 2 1 
  1 3 3 1 
 1 4 6 4 1 
1 5 10 10 5 1 None


Exercise3: The Tower of Hanoi is a mathematical problem that consists of three rods and multiple disks. Initially, all the disks are placed on one rod, one over the other in ascending order of size similar to a cone-shaped tower.

The objective of this problem is to move the stack of disks from the initial rod to another rod, following these rules:

A disk cannot be placed on top of a smaller disk
No disk can be placed on top of the smaller disk.
The goal is to move all the disks from the leftmost rod to the rightmost rod.

Your task is to write a recursive function hanoi_tower(n) to calculate the minimum moves that need to be performed to achieve the goal

# Chapter5: Dictionaries

Ex2: You are given a text. Write a program to print all the words in the text, one for each line. Words should be sorted in descending order of their number of occurrences in the text. Those words with the same number of occurrences should be sorted in lexicographic order.

In [ ]:
counts={}
text = []
while True:
    line=input()
    if line:
        text.append(line)
    else:
        break
print(text)
for i in range(len(text)):
    for word in text[i].split():
        counts[word]=counts.get(word,0)+1
to_sort=[(-v,k) for (k,v) in counts.items()]
for c, word in sorted(to_sort):
     print(word)

You are given a text. A word is a sequence of non-blank consecutive characters. Words are separated by one or more spaces or end-of-line characters. For each word from this text, you have to count how many times it has occurred earlier in this text.

In [ ]:
counts={}
text = []
while True:
    try:
        text.append(input())
    except:
        break
for i in range(len(text)):
    for word in text[i].split():
        counts[word]=counts.get(word,0)+1
        print(counts[word]-1,end=' ')

# Practice 5: Classes, objects and exceptions

First, we have a base class named Figure:

import math

class Figure:
    def perimeter(self):
        pass
    
    def area(self):
        pass

Write 3 classes named Rectangle, Circle, and Triangle that overwrite the perimeter and area methods of class Figure. You should also write an initialization method for each class

Rectangle should have 2 attributes: width and height
Circle should have 1 attribute: radius
Triangle should have 3 attributes: a, b, and c, which are the lengths of 3 sides
Exception:

Raise LengthException if any of the attributes above is less than or equal to 0
Raise InvalidTriangleException if the 3 lengths do not create a valid triangle
When an exception is caught (except LengthException as e:), print out the message that contains the type of that exception: print(str(type(e)) + ' was raised)
For example:

Test	Result
rec = Rectangle(-1, 2)
tri = Triangle(3, 4, 7)
<class '__main__.LengthException'> was raised
<class '__main__.InvalidTriangleException'> was raised
rec = Rectangle(1, 2)
tri = Triangle(3, 4, 5)
print(rec.perimeter())
print(tri.area())
6
6.0

In [ ]:
from math import sqrt
from math import pi


class Figure:
    def perimeter(self):
        pass

    def area(self):
        pass
class LengthException(Exception):
    pass
class InvalidTriangleException(Exception):
    pass

class Rectangle(Figure):
    def __init__(self, width, height):
        try:
            if width>0 and height>0:
                self.width=width
                self.height=height
            else:
                raise LengthException
        except LengthException as e:
            print(str(type(e))+' was raised')
    def perimeter(self):
        return (self.width+self.height)*2
    def area(self):
        return self.width*self.height
class Circle(Figure):
    def __init__(self,r):
        try:
            if r>0:
                self.r=r
            else:
                raise LengthException
        except LengthException as e:
            print(print(str(type(e))+' was raised'))
    def perimeter(self):
        return 2*pi*self.r
    def area(self):
        return pi*self.r*self.r

class Triangle(Figure):
    def __init__(self,a,b,c):
        try:
            if (a>0) and (b>0) and (c>0):
                if (a+b)>c and (b+c)>a and (c+a)>b:
                    self.a=a
                    self.b=b
                    self.c=c
                else:
                    raise InvalidTriangleException
            else:
                raise LengthException
        except LengthException as e:
            print(str(type(e)) + ' was raised')
        except InvalidTriangleException as e:
            print(str(type(e)) + ' was raised')

    def perimeter(self):
        return self.a+self.b+self.c
    def area(self):
        a,b,c=self.a, self.b, self.c
        return sqrt((a+b+c)*(a+b-c)*(b+c-a)*(c+a-b)/16)
rec = Rectangle(1, 2)
tri = Triangle(3, 4, 5)
print(rec.perimeter())
print(tri.area())        

6
6.0


Write 3 methods inside Triangle class to get the heights of the triangle. It should be named get_height_a, get_height_b, and get_height_c

For example:

Test	Result
t = Triangle(3, 4, 5)
print(t.get_height_a(), t.get_height_b(), t.get_height_c())
4.0 3.0 2.4


In [ ]:
import math


class Figure:
    def perimeter(self):
        pass

    def area(self):
        pass


class Triangle(Figure):
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c

    def perimeter(self):
        return self.a + self.b + self.c

    def area(self):
        p = self.perimeter() / 2
        return math.sqrt(p * (p - self.a) * (p - self.b) * (p - self.c))

    def get_height_a(self):
        return 2 * self.area() / self.a

    def get_height_b(self):
        return 2 * self.area() / self.b

    def get_height_c(self):
        return 2 * self.area() / self.c

Write 2 methods set_width and set_height inside class Rectangle to change the width and height of the rectangle object

In [ ]:
import math


class Figure:
    def perimeter(self):
        pass

    def area(self):
        pass


class Rectangle(Figure):
    def __init__(self, width, height):
        self.width = width
        self.height = height

    def perimeter(self):
        return (self.width + self.height) * 2

    def area(self):
        return self.width * self.height
    def set_width(self,new_width):
        self.width=new_width
    def set_height(self,new_height):
        self.height=new_height
        
        

Define a new class Square that inherits from class Rectangle. Write ONLY THE INITIALIZATION METHOD for that class with one input parameter (which is the side of the square), so that the methods perimeter and area can still be used. The Square class still uses the attributes width and height from the class Rectangle. The class Rectangle is inside Rectangle.py (code from the previous exercise) which has already been uploaded to the system.

In [ ]:
from Rectangle import Rectangle

class Square(Rectangle):
    def __init__(self, side_length):
        Rectangle.__init__(self, side_length, side_length

# Practice 4

In [ ]:
import numpy as np

a = np.arange(1, 21)

a = (((a - 1) * 5) % 19 + 1).reshape(4, 5)
a[3, 4] = 20
print(a)

[[ 1  6 11 16  2]
 [ 7 12 17  3  8]
 [13 18  4  9 14]
 [19  5 10 15 20]]


In [ ]:
import numpy as np
def convert(a):
    res = np.array(a[0] / np.sum(a[0]))
    
    for i in range(1, a.shape[0]):
        res = np.concatenate( (res, a[i] / np.sum(a[i])))
    return res.reshape(a.shape)
print(convert(np.arange(0, 9).reshape(3, 3)))    

[[0.         0.33333333 0.66666667]
 [0.25       0.33333333 0.41666667]
 [0.28571429 0.33333333 0.38095238]]


In [ ]:
import numpy as np

b = np.array([10, 100])
print(b[:,None])

[[ 10]
 [100]]
